### ISSUE TITLE
Update Library Versions to Resolve App Startup Issue

### ISSUE THREAD

**Issue by miraccan00** [weibenfalk/react-quiz#22]
Hi, could you update the project library versions? I couldn't start the app. Thanks!

**Comment by weibenfalk** [comment]
It was very outdated so I updated everything to Vite instead ... use "npm
run dev" to start the app.



Den tis 9 juli 2024 kl 21:00 skrev Mirac Can Yılmaz <
***@***.***>:

**Comment by miraccan00** [comment]
It's working thanks a lot :)
